USE [master]
GO

CREATE DATABASE APINoEFCore
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'APINoEFCore', FILENAME = N'/var/opt/mssql/data/APINoEFCore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'APINoEFCore_log', FILENAME = N'/var/opt/mssql/data/APINoEFCore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [APINoEFCore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [APINoEFCore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [APINoEFCore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [APINoEFCore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [APINoEFCore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [APINoEFCore] SET ARITHABORT OFF 
GO

ALTER DATABASE [APINoEFCore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [APINoEFCore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [APINoEFCore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [APINoEFCore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [APINoEFCore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [APINoEFCore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [APINoEFCore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [APINoEFCore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [APINoEFCore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [APINoEFCore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [APINoEFCore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [APINoEFCore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [APINoEFCore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [APINoEFCore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [APINoEFCore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [APINoEFCore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [APINoEFCore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [APINoEFCore] SET RECOVERY FULL 
GO

ALTER DATABASE [APINoEFCore] SET  MULTI_USER 
GO

ALTER DATABASE [APINoEFCore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [APINoEFCore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [APINoEFCore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [APINoEFCore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [APINoEFCore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [APINoEFCore] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [APINoEFCore] SET QUERY_STORE = ON
GO

ALTER DATABASE [APINoEFCore] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [APINoEFCore] SET  READ_WRITE 
GO


USE APINoEFCore
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/*Create Table Product*/
CREATE TABLE [Product](
	Id uniqueidentifier NOT NULL,
	Name nvarchar(max) NOT NULL,
	Price decimal(5, 2) NOT NULL,
	CreatedAt datetime2(7) NOT NULL,
 CONSTRAINT PK_Product PRIMARY KEY CLUSTERED 
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/*Insert on Product*/
INSERT INTO [Product]
           (Id,Name,Price,CreatedAt)
     VALUES
           ('6F8E9522-2693-4517-AB05-5814FEF799F9','Product 1',2.00,GETDATE()),
		   ('36B119C3-55FA-42FC-948D-F7F314CBDA60','Product 2',5.00,GETDATE())
GO

/*Create Table Person*/
CREATE TABLE [Person](
	Id uniqueidentifier NOT NULL,
      Name nvarchar(max) NOT NULL,
      Email nvarchar(max) NOT NULL,
      PasswordHash varchar(max) NOT NULL,
      Salt varchar(max) NOT NULL,
	IsAdmin bit NOT NULL,
	CreatedAt datetime2(7) NOT NULL,
 CONSTRAINT PK_Person PRIMARY KEY CLUSTERED 
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/*Insert on Person*/
INSERT INTO [Person]
			(Id, Name, Email, PasswordHash, Salt, IsAdmin, CreatedAt)
     VALUES
           ('690D5EEE-EF40-40A2-9BE4-CD8610C2692C', 'Person 1', 'person1@api.com', 'JgiD2Jk76+mqYxwvs4oWe0NygsMN/Qvs2jqrlfG24Rk=', 'wObeu7Rm8/wwNSxKpEZQjyaPIpYfWNgt/koT66QJ7c8=', 1, GETDATE()),
           ('CEB0B506-A565-4C9F-9F92-ED08B949F23B', 'Person 2', 'person2@api.com', 'ZczMrUVJSSYRwlBuz7AZhpgLiuHhoqxUb5gO1MQxhVs=', 'sq3lPqq+py2nF3aeILKdo9LwNUwT15BLmXTqPytM/5s=', 0, GETDATE())
GO

/*Create Table Order*/
CREATE TABLE [Order](
	Id uniqueidentifier NOT NULL,
	PersonId uniqueidentifier NOT NULL,
	ProductId uniqueidentifier NOT NULL,
	Qty int NOT NULL,
	Total decimal(5, 2) NOT NULL,
	CreatedAt datetime2(7) NOT NULL,
 CONSTRAINT PK_Order PRIMARY KEY CLUSTERED 
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [Order]  WITH CHECK ADD  CONSTRAINT FK_Order_Person_PersonId FOREIGN KEY(PersonId)
REFERENCES dbo.Person (Id)
ON DELETE CASCADE
GO

ALTER TABLE [Order] CHECK CONSTRAINT FK_Order_Person_PersonId
GO

ALTER TABLE [Order]  WITH CHECK ADD  CONSTRAINT FK_Order_Product_ProductId FOREIGN KEY(ProductId)
REFERENCES dbo.Product (Id)
ON DELETE CASCADE
GO

ALTER TABLE [Order] CHECK CONSTRAINT FK_Order_Product_ProductId
GO

/*Insert on Orders*/
INSERT INTO [Order]
           (Id, PersonId, ProductId, Qty, Total, CreatedAt)
     VALUES
           ('98DBDAA4-6C3F-47F4-B293-EE68ADE2B102', '690D5EEE-EF40-40A2-9BE4-CD8610C2692C', '6F8E9522-2693-4517-AB05-5814FEF799F9', 10, 20.00, GETDATE())
GO

CREATE PROCEDURE [CreateOrder]
@PersonId UNIQUEIDENTIFIER,
@ProductId UNIQUEIDENTIFIER,
@Qty INT
AS
BEGIN
    DECLARE @Price DECIMAL(5, 2)
    DECLARE @NewGuid UNIQUEIDENTIFIER
    DECLARE @CurrentDateTime DATETIME2(7)

    -- Get Price from Product table
    SELECT @Price = Price
    FROM Product
    WHERE Id = @ProductId

    -- Calculate Total
    DECLARE @Total DECIMAL(5, 2)
    SET @Total = @Price * @Qty

    -- Generate new Guid and current DateTime
    SET @NewGuid = NEWID()
    SET @CurrentDateTime = SYSDATETIME()

    -- Insert into Order table
    INSERT INTO [Order] (Id, PersonId, ProductId, Qty, Total, CreatedAt)
    VALUES (@NewGuid, @PersonId, @ProductId, @Qty, @Total, @CurrentDateTime)                                       
END
GO





